# .github/workflows/gh-pages-mac.yml

name: Build & Deploy to GitHub Pages (macOS)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Emscripten SDK
        uses: emscripten-core/emsdk@v3
        with:
          emsdk_version: latest

      - name: Build BigNum WebAssembly & JS
        working-directory: ./web
        run: |
          # Make sure your build_wasm.sh is executable and in web/
          chmod +x build_wasm.sh
          ./build_wasm.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
